### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by sirkitree** [j-hannah/jsReport#15]
Here's my first crack at this. I'd like to sit on it a little while before we add it, maybe get @jponch's thoughts on it.

![jsreport](https://cloud.githubusercontent.com/assets/28543/23873625/4e086fa6-07f8-11e7-97ff-9543b534871a.png)

This is loosely based off of the JS Foundation logo. It's pretty typical to see the JS logo remixed like this. I'm also using Lullabot red.

Here's the Typical JS logo: ![img](http://3.bp.blogspot.com/-PTty3CfTGnA/TpZOEjTQ_WI/AAAAAAAAAeo/KeKt_D5X2xo/s1600/js.jpg)

Here's the JS Foundation logo: ![img](https://dab1nmslvvntp.cloudfront.net/wp-content/uploads/2017/03/1488968009jsf-logo.png)

**Comment by jponchot** [comment]
I feel like I'm coming into this having missed some conversations or something as I wasn't really sure what this was even. Is this a logo for something Lullabot does? What is a JS Report? Again, sorry if there's an email thread I somehow dropped or something that's left me ignorant :)

**Comment by sirkitree** [comment]
Sorry @jponchot, we're coming up with this and hope to launch this project in conjunction with some of our other JS initiatives (not anytime soon). This was just an attempt to get it on your radar. We don't have a logo right now for it, which is just fine, I was just brainstorming what one might look like.

JS Report is going to be our effort to curate JS articles from the community into an email list with a website archive and collect some learning resources to boot. Nothing pressing, and not even an official Lullabot project at this point. SO really I'm just looking for your opinions on my first attempt at a logo considering it's not Lullabot affiliated, at least not yet.

**Comment by jponchot** [comment]
Ah, ok cool. Yeah, the name sounds like an Email Newsletter sort of thing for sure. I can try playing with Lullabot's typographic system along with the JS mark you've referenced here. Is there a target date for when the first issue of emails will first go out @sirkitree? Also, is this something where we will need to design some sort of special component encouraging sign-up for this on all js related articles or something? Curious to get @ellie involved at some point as well as she'll likely keep an eye on all our lists etc. and what we do with them.

**Comment by sirkitree** [comment]
> Is there a target date for when the first issue of emails will first go out @sirkitree?

No target at this point. We want to get the basic tech in place and then coordinate a launch with Ellie.

> Also, is this something where we will need to design some sort of special component encouraging sign-up for this on all js related articles or something? 

I don't think we'd have to design anything really. I was going to mimic the one on Lullabot.com, maybe without the robot.
![articles lullabot 2017-03-16 19-52-20](https://cloud.githubusercontent.com/assets/28543/24025760/1bf9f84a-0a82-11e7-85d4-f9098d823fd4.png)

> Curious to get @ellie involved at some point as well as she'll likely keep an eye on all our lists etc. and what we do with them.

Most certainly. We want to get the tech ready first, then coordinate with her.

**Comment by j-hannah** [comment]
@jponchot @sirkitree To clarify, this is totally non-sanctioned and possibly not welcome. It was suggested that anything representing Lullabot as "javascript" or outside the context of the full range of services we offer may confuse branding.

The primary purpose of this project is to provide a way for Lullabot devs to get involved/active in the JS community and secondarily provide a project for us to work on together and try some interesting stuff out. 

My hope is that if we do this well, we might get sponsorship from Lullabot (meaning they'd pay the hosting costs) and maybe that would drum up some business. From my conversations with Seth, there isn't much interest from Lullabot in doing a JS blog and not much interest from Ellie in doing a JS only newsletter.

Just wanted to share that bit of back story as it may be relevant. I'm not sure Ellie is going to be that excited to hear this is happening, actually. But it's not a Lullabot thing at this point. I would be happy if that happens, but not optimistic.

**Comment by sirkitree** [comment]
> and possibly not welcome. It was suggested that anything representing Lullabot as "javascript" or outside the context of the full range of services we offer may confuse branding.

I'm sorry someone gave you this impression. I've never had anything but support from Lullabot for diving into projects like this. JavaScript is a service we provide and something like this is a valid way to try to gain more business. But you're right, the primary purpose is for us. But if we can build something for ourselves and provide a valuable service and possibly gain leads out of it, then I think we're doing Lullabot a service overall. We're not asking anyone to do anything they don't want to do (@jponchot if you have no interest feel free to ignore us, no hard feelings).

But I am optimistic that this is valuable and that discouraging efforts like this does more harm than good. But we digress...

THe current logo is a wordmark and that is sufficient for now.

**Comment by theodorosploumis** [comment]
Hi, I could help with this if you like. I "know" Lullabot and @j-hannah because of Drupal for years now.
I am not a professional logo designer but I like creating logos and graphics for open source projects. If you are interested on this let me know.

Thanks!

**Comment by elliebot1** [comment]
@j-hannah @sirkitree Hi guys! My apologies for jumping in here late in the game. Now that I've read this thread, I have a lot more context around the JS newsletter. I'm sorry if you feel unsupported as that is certainly not my intent. I suggest we hop on a call and discuss the possibilities based on what you guys are aiming to accomplish and so I can better explain my thoughts from a branding/marketing perspective. I think there are some cool things we can do with all of this!

**Comment by j-hannah** [comment]
@theodorosploumis Thank you for your generous offer! For now, although it's a public repo on my account, we're staying in-house with the Lullabot team. It's much appreciated, though. 👍

**Comment by j-hannah** [comment]
Closing for now, but if plan for Lullabot support works out long term, we can circle back and perhaps get help from design team.
